name: Deploy Code Push

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy-code-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
          
      - name: Get NPM Version
        uses: nyaa8/package-version@v1
        
      - name: Install app dependencies
        uses: bahmutov/npm-install@v1
                
      - name: Generate .env
        run: |-
          echo CODE_PUSH_DEPLOYMENT_KEY_ANDROID=${{ secrets.CODE_PUSH_DEPLOYMENT_KEY_ANDROID }} >> .env
          
      - name: Install AppCenter CLI
        run: npm install appcenter-cli
        
      - name: Deploy to CodePush Android
        run: npx appcenter codepush release-react -a most_random_user_ever/GeoMessenger -d Production --mandatory true
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN_ANDROID }}
